CREATE TABLE IF NOT EXISTS friend_status (
 status_id INTEGER NOT NULL PRIMARY KEY,
 status VARCHAR NOT NULL
);

INSERT INTO friend_status (status_id, status)
SELECT 1, 'confirmed'
WHERE NOT EXISTS (SELECT 1 FROM friend_status WHERE status_id = 1);

INSERT INTO friend_status (status_id, status)
SELECT 2, 'unconfirmed'
WHERE NOT EXISTS (SELECT 1 FROM friend_status WHERE status_id = 2);

CREATE TABLE IF NOT EXISTS genre (
 genre_id INTEGER NOT NULL PRIMARY KEY,
 genre VARCHAR NOT NULL
);

INSERT INTO genre (genre_id, genre)
SELECT 1, 'Комедия'
WHERE NOT EXISTS (SELECT 1 FROM genre WHERE genre_id = 1);

INSERT INTO genre (genre_id, genre)
SELECT 2, 'Драма'
WHERE NOT EXISTS (SELECT 1 FROM genre WHERE genre_id = 2);

INSERT INTO genre (genre_id, genre)
SELECT 3, 'Мультфильм'
WHERE NOT EXISTS (SELECT 1 FROM genre WHERE genre_id = 3);

INSERT INTO genre (genre_id, genre)
SELECT 4, 'Триллер'
WHERE NOT EXISTS (SELECT 1 FROM genre WHERE genre_id = 4);

INSERT INTO genre (genre_id, genre)
SELECT 5, 'Документальный'
WHERE NOT EXISTS (SELECT 1 FROM genre WHERE genre_id = 5);

INSERT INTO genre (genre_id, genre)
SELECT 6, 'Боевик'
WHERE NOT EXISTS (SELECT 1 FROM genre WHERE genre_id = 6);

CREATE TABLE IF NOT EXISTS rating_mpa (
 rating_mpa_id INTEGER NOT NULL PRIMARY KEY,
 rating_mpa VARCHAR NOT NULL
);

INSERT INTO rating_mpa (rating_mpa_id, rating_mpa)
SELECT 1, 'G'
WHERE NOT EXISTS (SELECT 1 FROM rating_mpa WHERE rating_mpa_id = 1);

INSERT INTO rating_mpa (rating_mpa_id, rating_mpa)
SELECT 2, 'PG'
WHERE NOT EXISTS (SELECT 1 FROM rating_mpa WHERE rating_mpa_id = 2);

INSERT INTO rating_mpa (rating_mpa_id, rating_mpa)
SELECT 3, 'PG-13'
WHERE NOT EXISTS (SELECT 1 FROM rating_mpa WHERE rating_mpa_id = 3);

INSERT INTO rating_mpa (rating_mpa_id, rating_mpa)
SELECT 4, 'R'
WHERE NOT EXISTS (SELECT 1 FROM rating_mpa WHERE rating_mpa_id = 4);

INSERT INTO rating_mpa (rating_mpa_id, rating_mpa)
SELECT 5, 'NC-17'
WHERE NOT EXISTS (SELECT 1 FROM rating_mpa WHERE rating_mpa_id = 5);

-- =========================================================================

CREATE TABLE IF NOT EXISTS users (
 user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email VARCHAR UNIQUE NOT NULL,
 login VARCHAR UNIQUE NOT NULL,
 username VARCHAR NOT NULL,
 birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
 film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 film_name VARCHAR NOT NULL,
 description TEXT NOT NULL CHECK (LENGTH(description) <= 200),
 release_date DATE NOT NULL,
 duration INTEGER CHECK (duration >= 0 AND NOT NULL),
 rating_mpa_id INTEGER REFERENCES rating_mpa (rating_mpa_id) ON DELETE RESTRICT
);

-- =========================================================================

CREATE TABLE IF NOT EXISTS friends (
 user_id_1 INTEGER NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
 user_id_2 INTEGER NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
 status_id INTEGER NOT NULL REFERENCES friend_status (status_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS film_genre (
 film_id INTEGER NOT NULL REFERENCES films (film_id) ON DELETE CASCADE,
 genre_id INTEGER NOT NULL REFERENCES genre (genre_id) ON DELETE RESTRICT
);

-- =========================================================================

CREATE TABLE IF NOT EXISTS liked_films (
 user_id INTEGER NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
 film_id INTEGER NOT NULL REFERENCES films (film_id) ON DELETE CASCADE
);